version: "3.1"
services:

  database:
    image: mysql:5.7
    volumes:
      - ./main/resources:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=test"
      - "MYSQL_DATABASE=organisatoren"
