== Abschnitt 3 Kontextabgrenzung
=== Aufgabe 3.1 Fachlicher Kontext

==== Studenten (Benutzer)

Der Student bekommt eine Mail mit einer Zulassungsbenachrichtigung und dem zugehörigen Token, nachdem er die Klausurzulassung bestanden hat.
Der Student kann den Token auf der Weboberfläche einlösen, wenn er sich zur neuen Klausur zulassen möchte.
Er bekommt eine visuelle Bestätigung ob dies erfolgreich war.

==== Organisator (Benutzer)

Der Organisator kann eine Liste mit zugelassenen Studenten in das System hochladen.
Anschließend werden für ihn vollkommen automatisch die Token versendet.
Ebenso muss sich der Organisator nicht mehr um Altzulassungen kümmern, diese werden selbstständig für ihn verwaltet.
Vor einer Klausur kann sich der Organisator einfach eine Liste herunterladen, in welcher allen zugelassenen Studenten stehen.

=== Aufgabe 3.2 Technischer Kontext

==== Tokengenerierung

Die Token werden durch asymmetrische Kryptographie verschlüsselt.
Durch diesen hohen Sicherheitsstandard ist es nicht möglich eine Quittung zu fälschen.

==== Tokenverifikation

Durch die asymmetrische Verschlüsselung wird nur ein Public Key benötigt, um die Token zu verifizieren, Passwörter müssen nicht gespeichert werden.

==== Email-Service

Es ist ein Email Service implementiert, der automatisch den Studenten die generierten Token versendet.
Es ist kein Handeln der Organisatoren nötig.
Dadurch können keine Fehler beim Versenden entstehen und bürokratischer Aufwand gegenüber früher verschwindet.

==== Statistik

Es existiert in der Anwendung zu jedem Modul eine Statistik. Diese gibt grafisch Rückmeldung über die Teilnehmer und davon zur Klausur
zugelassenen Studenten. Es wird der Trend der letzten Jahre visualisiert.

==== Key-Cloak (Fremdsystem)

Key-Cloak sorgt für die Sicherheit des Systems.
Es implementiert ein Benutzersystem, sodass sich Studenten oder Organisatoren anmelden.
Diese Nutzer können anschließend nur auf die für Sie vorgesehene Inhalte zugreifen.
Key-Cloak ist als externes System auf Sicherheit optimiert.